[buildPlans.Tempestypes]
family = "Tempestypes"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.Tempestypes.variants.design]
two = "straight-neck-serifless"
three = "flat-top-serifless"
four = "closed-serifless"
zero = "oval-dotted"
capital-m = "flat-bottom-serifless"
capital-q = "vertical-crossing"
capital-w = "straight-flat-top-serifless"
a = "single-storey-top-cut-serifless"
f = "flat-hook-extended"
g = "single-storey-top-cut"
i = "hooky"
r = "hookless-serifless"
t = "bent-hook-short-neck2"
w = "straight-flat-top-serifless"
y = "cursive-serifless"
long-s = "flat-hook-tailed"
lower-delta = "flat-top"
lower-mu = "toothed-serifless"
lower-pi = "tailless"
lower-tau = "tailed"
cyrl-a = "single-storey-top-cut-serifed"
tittle = "square"
diacritic-dot = "square"
punctuation-dot = "square"
braille-dot = "square"
asterisk = "hex-low"
paren = "large-contour"
brace = "curly-flat-boundary"
guillemet = "straight"
ampersand = "flat-top"
at = "compact"
percent = "rings-continuous-slash"
question = "corner"
pilcrow = "curved"
partial-derivative = "curly-bar"
decorative-angle-brackets = "tall"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

  [buildPlans.Tempestypes.ligations]
  inherits = "dlig"

[buildPlans.Tempestypes.weights.Thin]
shape = 100
menu = 100
css = 100

[buildPlans.Tempestypes.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Tempestypes.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Tempestypes.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Tempestypes.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.Tempestypes.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
